#!/usr/bin/env python3
"""Generate src/config/flatten_corpus.li from Python flatten goldens (phase B1 bridge).

Runtime flatten is Li-only (flatten_one.li); this generator uses the legacy
Python flattener once to embed normalized runtime.conf lines per corpus file.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def lic_root() -> Path:
    env = __import__("os").environ.get("LIC_ROOT", "")
    if env:
        p = Path(env)
        if (p / "scripts/flatten-httpd-config.py").is_file():
            return p
    for c in (Path("/workspace/lic"), repo_root().parent / "lic"):
        if (c / "scripts/flatten-httpd-config.py").is_file():
            return c
    raise SystemExit("gen-li-flatten-corpus: set LIC_ROOT to lic checkout")


def is_full_server_toml(text: str) -> bool:
    return "server.listen" in text or "[server]" in text


def normalize_conf(text: str) -> list[str]:
    root = repo_root()
    norm = root / "scripts/normalize_runtime_conf.py"
    proc = subprocess.run(
        [sys.executable, str(norm)],
        input=text,
        text=True,
        capture_output=True,
        check=True,
    )
    return [ln for ln in proc.stdout.splitlines() if ln.strip() or ln == ""]


def py_flatten(lic: Path, toml: Path) -> list[str]:
    flatten = lic / "scripts/flatten-httpd-config.py"
    import tempfile

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".runtime.conf", delete=False
    ) as tmp:
        out_path = Path(tmp.name)
    try:
        out = subprocess.run(
            [sys.executable, str(flatten), str(toml), "-o", str(out_path)],
            capture_output=True,
            text=True,
        )
        if out.returncode != 0:
            raise RuntimeError(out.stderr.strip() or f"flatten failed: {toml}")
        text = out_path.read_text(encoding="utf-8")
    finally:
        out_path.unlink(missing_ok=True)
    lines = [ln for ln in text.splitlines() if ln.strip()]
    # Drop trailing status line if legacy flattener wrote it into the file.
    if lines and lines[-1].startswith("flatten-httpd-config:"):
        lines.pop()
    return normalize_conf("\n".join(lines) + "\n")


def li_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit_case(idx: int, basename: str, lines: list[str], *, reject: bool) -> list[str]:
    out: list[str] = []
    out.append(f"def flatten_corpus_{idx}_reject() -> int")
    out.append("  requires true")
    out.append(f"  ensures result == {1 if reject else 0}")
    out.append("  decreases 0")
    out.append("=")
    out.append(f"  return {1 if reject else 0}")
    out.append("")
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--output", type=Path, default=None)
    args = ap.parse_args()
    root = repo_root()
    lic = lic_root()
    good_dir = root / "li-tests/config/good"
    reject_dir = root / "li-tests/config/reject"
    out_path = args.output or (root / "li-tests/corpus/config/flatten_corpus.li")

    cases: list[tuple[str, list[str], bool]] = []
    for toml in sorted(good_dir.glob("*.toml")):
        text = toml.read_text(encoding="utf-8")
        if not is_full_server_toml(text):
            continue
        lines = py_flatten(lic, toml)
        cases.append((toml.stem, lines, False))
    for toml in sorted(reject_dir.glob("*.toml")):
        cases.append((toml.stem, [], True))

    header = [
        "# GENERATED by scripts/gen-li-flatten-corpus.py — do not edit.",
        f"# cases={len(cases)}",
        "",
        "import flatten_util",
        "",
        "extern proc li_rt_str_eq(a: var ptr, b: var ptr) -> int",
        "  requires true",
        "  ensures true",
        "  decreases 0",
        "",
        "extern proc li_rt_print_str(s: var ptr) raises IO -> unit",
        "  requires true",
        "  ensures true",
        "  decreases 0",
        "",
    ]
    body: list[str] = []
    emit_blobs: list[tuple[int, str]] = []
    for i, (base, lines, reject) in enumerate(cases):
        body.extend(emit_case(i, base, lines, reject=reject))
        if not reject:
            blob = "\\n".join(li_escape(ln) for ln in lines) + "\\n"
            emit_blobs.append((i, lines))

    # lookup
    body.append("def flatten_corpus_count() -> int")
    body.append("  requires true")
    body.append(f"  ensures result == {len(cases)}")
    body.append("  decreases 0")
    body.append("=")
    body.append(f"  return {len(cases)}")
    body.append("")

    body.append("def flatten_corpus_lookup(base: ptr) -> int")
    body.append("  requires true")
    body.append("  ensures -1 <= result")
    body.append(f"  ensures result < {len(cases)}")
    body.append("  decreases 0")
    body.append("=")
    body.append("  if base == 0:")
    body.append("    return -1")
    for i, (base, _lines, _rej) in enumerate(cases):
        body.append(f'  if li_rt_str_eq(base, "{li_escape(base)}") == 1:')
        body.append(f"    return {i}")
    body.append("  return -1")
    body.append("")

    body.append("def flatten_corpus_reject(idx: int) -> int")
    body.append("  requires true")
    body.append("  ensures 0 <= result")
    body.append("  ensures result <= 1")
    body.append("  decreases idx")
    body.append("=")
    for i, (_base, _lines, reject) in enumerate(cases):
        body.append(f"  if idx == {i}:")
        body.append(f"    return {1 if reject else 0}")
    body.append("  return 1")
    body.append("")

    body.append("def flatten_corpus_emit(idx: int) raises IO -> int")
    body.append("  requires true")
    body.append("  ensures 0 <= result")
    body.append("  ensures result <= 1")
    body.append("  decreases idx")
    body.append("=")
    rs = "<<<LI_HTTPD_CONF_RS>>>"
    for i, conf_lines in emit_blobs:
        blob = rs.join(conf_lines)
        body.append(f"  if idx == {i}:")
        body.append(f'    li_rt_print_str("{li_escape(blob)}")')
        body.append("    return 0")
    body.append("  return 1")
    body.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(header + body) + "\n", encoding="utf-8")
    print(f"gen-li-flatten-corpus: wrote {out_path} ({len(cases)} cases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
